GET http://localhost:5000/list-todo
# menampilkan semua data pada tabel

###
GET http://localhost:5000/list-todo/1
# menampilkan data dengan id tertentu

###
POST http://localhost:5000/list-todo
# menambahkan data pada tabel
Content-Type: application/json

{
    "item": "Kuliahh",
    "kondisi": "mendadak",
    "deadline": "20/09/2090"
}


###
PATCH  http://localhost:5000/list-todo/7
# update data pada tabel
Content-Type: application/json

{
    "item": "ngopi",
    "kondisi": "santuy",
    "dedline": "30/12/2022"
}


###
DELETE  http://localhost:5000/list-todo/11
# hapus data pada tabel
