GET http://localhost:5000/list-todo
# menampilkan semua data pada tabel

###
GET http://localhost:5000/list-todo/4
# menampilkan data dengan id tertentu

###
POST http://localhost:5000/list-todo
# menambahkan data pada tabel
Content-Type: application/json

{
    "item": "Kuliahh",
    "kondisi": "mendadak",
    "deadline": "20/09/2090"
}


###
PATCH  http://localhost:5000/list-todo/4
# update data pada tabel
Content-Type: application/json

{
    "item": "rapat",
    "kondisi": "santuy",
    "deadline": "20/09/2090"
}

###
DELETE  http://localhost:5000/list-todo/10
# hapus data pada tabel
Content-Type: application/json

{
    "item": "Kuliah",
    "kondisi": "penting"
}